repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: python -m pylint src
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: python -m pytest tests
        language: system
        types: [python]
