repos:
  - repo: local
    hooks:
      - id: pylint src
        name: pylint src
        entry: python -m pylint src
        language: system
        types: [python]
      - id: pylint tests
        name: pylint tests
        entry: python -m pylint tests
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: python -m pytest tests
        language: system
        types: [python]
