name: 'Test and build a Python application'

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint source and tests
        run: |
          python -m pylint src
          python -m pylint tests
      - name: Test
        run: python -m pytest tests
      - name: Compute coverage
        run: |
          coverage run --data-file .coverage/data -m pytest tests
          coverage html --data-file .coverage/data -d .coverage/html
          coverage xml --data-file  .coverage/data -o .coverage/xml
          genbadge coverage -i .coverage/xml -o .badges/coverage-badge.svg
